CREATE TABLE user_group (
  id int(16) NOT NULL AUTO_INCREMENT,
  userid int(16) NOT NULL COMMENT '用户id',
  groupid int(16) NOT NULL COMMENT '组id',
  PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8;