CREATE TABLE user_role (
  id int(16) NOT NULL AUTO_INCREMENT,
  userid int(16) NOT NULL COMMENT '用户id',
  roleid int(16) NOT NULL COMMENT '角色id',
  PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8;